name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ubuntu-latest
    services:
      fakepod:
        image: ghcr.io/takeyaqa/fakepod:0.2.1
        ports:
          - 3000:3000
      bigquery-emulator:
        image: ghcr.io/goccy/bigquery-emulator:latest
        env:
          BIGQUERY_EMULATOR_PROJECT: fake-project
        ports:
          - 9050:9050
      fake-gcs-server:
        image: fsouza/fake-gcs-server:latest
        ports:
          - 4443:4443
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: yarn test
        env:
          BIGQUERY_EMULATOR_HOST: http://localhost:9050
          NODE_TLS_REJECT_UNAUTHORIZED: 0
